import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { fetchSketchSlugs } from "../lib/fetchSketchSlugs";

export async function getStaticProps() {
  const data = await fetchSketchSlugs();
  const slugs = data.map((slug) => {
    return slug.replace(/\.tsx$/, "");
  });
  return {
    props: {
      ...slugs,
    },
  };
}

const Home = (slugs: string[]) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {(() => {
            const elem = [];
            for (let id in slugs) {
              elem.push(
                <li id={slugs[id]}>
                  <Link href={`/work/${slugs[id]}`}>{slugs[id]}</Link>
                </li>
              );
            }
            return elem;
          })()}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
